import sys
import os
from datetime import datetime

class SystemAudioNotifier:
    """Handles terminal bell beeps and system alert sounds on critical threat triggers."""
    @staticmethod
    def trigger_alert_sound():
        # Terminal Bell ASCII sequence for instant sound
        sys.stdout.write("\a")
        sys.stdout.flush()


class IntelligenceReportGenerator:
    """Generates automated Markdown Threat Intelligence Reports from active console memory."""
    @staticmethod
    def generate_markdown_report(recent_events, filepath="threat_briefing_report.md"):
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        report_content = f"""# TACTICAL THREAT INTELLIGENCE BRIEFING
**Generated At:** {timestamp}  
**Classification:** RESTRICTED // DEFENCE ANALYST BRIEF  

---

## 1. Executive Threat Summary
This automated intelligence report compiles correlated events captured by the Cyber Tactical Defence Console.

---

## 2. Recent Captured Threat Events

| Timestamp | Source Module | Severity / Risk | Summary / Raw Telemetry |
| :--- | :--- | :--- | :--- |
"""
        for event in recent_events:
            t_time = event.get("time", "N/A")
            t_type = event.get("type", "UNKNOWN")
            t_data = event.get("data", {})
            summary = t_data.get("raw_text", str(t_data))
            
            report_content += f"| {t_time} | {t_type} | HIGH/CRITICAL | {summary} |\n"

        report_content += """
---
## 3. Recommended Operational Directives
1. **Airspace Anomalies:** Maintain passive radar tracking on identified priority military callsigns.
2. **SIGINT Leaks:** Block identified domain indicators and monitor darkweb exfiltration channels.
3. **Infrastructure Security:** Patch exposed SCADA/ICS nodes and restrict unauthenticated database ports.

*Report automatically generated by Cyber Tactical Defence Console Engine v1.0.*
"""
        try:
            with open(filepath, "w") as f:
                f.write(report_content)
            return True, os.path.abspath(filepath)
        except Exception as e:
            return False, str(e)


class CommandProcessor:
    """Processes interactive shell commands entered into CTIE-SHELL."""
    def __init__(self, console_app):
        self.app = console_app

    async def execute_command(self, cmd_text):
        cmd_text = cmd_text.strip()
        if not cmd_text:
            return "No command entered."

        parts = cmd_text.split()
        base_cmd = parts[0].lower()

        if base_cmd == "help":
            return "AVAILABLE COMMANDS: lookup <IP> | track <CALLSIGN> | report | clear"

        elif base_cmd == "lookup" and len(parts) > 1:
            target_ip = parts[1]
            return f"[SHELL RECON] Target IP {target_ip} flagged: Exposed Ports [80, 443, 22] | ASN: AS13335 (Cloudflare)"

        elif base_cmd == "track" and len(parts) > 1:
            callsign = parts[1].upper()
            return f"[SHELL TRACK] Filtering radar array for Military Callsign: {callsign}... Locks Active."

        elif base_cmd == "report":
            recent = self.app.scorer.recent_events
            success, path = IntelligenceReportGenerator.generate_markdown_report(recent)
            if success:
                return f"[REPORT SUCCESS] Threat Briefing saved to: {path}"
            else:
                return f"[REPORT ERROR] Failed to save report: {path}"

        elif base_cmd == "clear":
            return "[SHELL] Logs cleared."

        else:
            return f"Unknown command: '{base_cmd}'. Type 'help' for available commands."
